---
- hosts: localhost
  become: yes
  
  tasks:

  
  - name: Create new ssh key-pair
    shell: ssh-keygen -b 2048 -t rsa -f /root/.ssh/priyanka-ubuntu1 -q -N ""
    args:
      creates: /root/.ssh/priyanka-ubuntu1
